# Generated by Django 5.2.7 on 2025-10-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('In_progress', 'In Progress'), ('Completed', 'Completed'), ('On_hold', 'On Hold')], default='in_progress', max_length=30),
        ),
    ]
