# Generated by Django 5.2.7 on 2025-10-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('In_Progress', 'In Progress'), ('Completed', 'Completed'), ('On_Hold', 'On Hold')], default='in_progress', max_length=30),
        ),
    ]
