# Generated by Django 5.2.7 on 2025-11-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In_progress'), ('Completed', 'Completed'), ('Not Started', 'Not_Started')], default='in_progress', max_length=30),
        ),
    ]
